apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"grafana","namespace":"observability"},"spec":{"ports":[{"nodePort":30300,"port":3000,"targetPort":3000}],"selector":{"app":"grafana"},"type":"NodePort"}}
  creationTimestamp: "2025-10-30T10:05:54Z"
  name: grafana
  namespace: observability
  resourceVersion: "1032"
  uid: 3fa9cdee-bb00-47f6-83e0-2275c47dacd1
spec:
  clusterIP: 10.100.36.231
  clusterIPs:
  - 10.100.36.231
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30300
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
