apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "7"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"otel-collector","namespace":"observability"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"otel-collector"}},"template":{"metadata":{"labels":{"app":"otel-collector"}},"spec":{"containers":[{"args":["--config=/etc/otel-collector-config.yaml"],"image":"otel/opentelemetry-collector-contrib:0.138.0","name":"otel-collector","ports":[{"containerPort":4317,"name":"grpc"},{"containerPort":4318,"name":"http"},{"containerPort":8889,"name":"metrics"}],"volumeMounts":[{"mountPath":"/etc/otel-collector-config.yaml","name":"config","subPath":"config.yaml"}]}],"volumes":[{"configMap":{"name":"otel-collector-config"},"name":"config"}]}}}}
  creationTimestamp: "2025-10-30T10:06:01Z"
  generation: 7
  name: otel-collector
  namespace: observability
  resourceVersion: "7178"
  uid: 53bf3e27-2046-4225-b1da-733d29c6c1aa
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: otel-collector
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-10-30T17:23:13+05:30"
      labels:
        app: otel-collector
    spec:
      containers:
      - args:
        - --config=/etc/otel-collector-config.yaml
        image: otel/opentelemetry-collector-contrib:0.138.0
        imagePullPolicy: IfNotPresent
        name: otel-collector
        ports:
        - containerPort: 4317
          name: grpc
          protocol: TCP
        - containerPort: 4318
          name: http
          protocol: TCP
        - containerPort: 8889
          name: metrics
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/otel-collector-config.yaml
          name: config
          subPath: config.yaml
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: otel-collector-config
        name: config
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-10-30T11:53:14Z"
    lastUpdateTime: "2025-10-30T11:53:14Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-10-30T10:06:01Z"
    lastUpdateTime: "2025-10-30T11:53:14Z"
    message: ReplicaSet "otel-collector-799c664588" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 7
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
