apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"tempo","namespace":"observability"},"spec":{"ports":[{"name":"http","port":3200,"targetPort":3200},{"name":"otlp-http","port":4318,"targetPort":4318}],"selector":{"app":"tempo"},"type":"ClusterIP"}}
  creationTimestamp: "2025-10-30T10:05:57Z"
  name: tempo
  namespace: observability
  resourceVersion: "1061"
  uid: 565c5555-dfff-4f72-837e-53a828c9db69
spec:
  clusterIP: 10.107.227.198
  clusterIPs:
  - 10.107.227.198
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 3200
    protocol: TCP
    targetPort: 3200
  - name: otlp-http
    port: 4318
    protocol: TCP
    targetPort: 4318
  selector:
    app: tempo
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
