apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"tempo","namespace":"observability"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"tempo"}},"template":{"metadata":{"labels":{"app":"tempo"}},"spec":{"containers":[{"args":["-config.file=/etc/tempo/tempo-config.yaml"],"image":"grafana/tempo:latest","name":"tempo","ports":[{"containerPort":3200,"name":"http"},{"containerPort":4318,"name":"otlp-http"}],"volumeMounts":[{"mountPath":"/etc/tempo","name":"config"},{"mountPath":"/var/tempo","name":"tempo-storage"}]}],"volumes":[{"configMap":{"name":"tempo-config"},"name":"config"},{"emptyDir":{},"name":"tempo-storage"}]}}}}
  creationTimestamp: "2025-10-30T10:05:57Z"
  generation: 2
  name: tempo
  namespace: observability
  resourceVersion: "6815"
  uid: a61a02e1-cea8-4626-9149-fbf1f4f1bef4
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: tempo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-10-30T17:11:56+05:30"
      labels:
        app: tempo
    spec:
      containers:
      - args:
        - -config.file=/etc/tempo/tempo-config.yaml
        image: grafana/tempo:latest
        imagePullPolicy: Always
        name: tempo
        ports:
        - containerPort: 3200
          name: http
          protocol: TCP
        - containerPort: 4318
          name: otlp-http
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/tempo
          name: config
        - mountPath: /var/tempo
          name: tempo-storage
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: tempo-config
        name: config
      - emptyDir: {}
        name: tempo-storage
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-10-30T10:05:57Z"
    lastUpdateTime: "2025-10-30T11:43:03Z"
    message: ReplicaSet "tempo-84f6476d44" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-10-30T11:47:44Z"
    lastUpdateTime: "2025-10-30T11:47:44Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
