apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"demo-app"},"name":"demo-app","namespace":"observability"},"spec":{"ports":[{"name":"http","port":8080,"targetPort":8080}],"selector":{"app":"demo-app"},"type":"ClusterIP"}}
  creationTimestamp: "2025-10-30T10:19:41Z"
  labels:
    app: demo-app
  name: demo-app
  namespace: observability
  resourceVersion: "2662"
  uid: fcb1eaed-7308-40b0-b985-a4980590e357
spec:
  clusterIP: 10.107.156.168
  clusterIPs:
  - 10.107.156.168
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: demo-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
